version: "3"

services:
  # REDIS CONFIGURATION
  redis:
    container_name: redis_instance
    image: "redis:alpine"
    ports:
    - "6379:6379"

  # EUREKA SERVER CONFIGURATION
  eurekaserver:
    container_name: eurekaserver
    build:
      context: ../../eurekaserver
      dockerfile: ./Dockerfile
    hostname: eurekaserver
    ports:
      - "8761:8761"

  # CONFIG SERVER CONFIGURATION
  configserver:
    container_name: configserver
    build:
      context: ../../configserver
      dockerfile: ./Dockerfile
    hostname: configserver
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
    ports:
      - "8888:8888"

  # NEWS SERVICE CONFIGURATION
  newsservice:
    container_name: newsservice
    build:
      context: ../../newsservice
      dockerfile: ./Dockerfile
    links:
      - eurekaserver
      - configserver
      - redis
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
      REDIS_HOST: 192.168.1.6
    ports:
      - "8881:8881"

  # GATEWAY SERVER CONFIGURATION
  gatewayserver:
    container_name: gatewayserver
    build:
      context: ../../gatewayserver
      dockerfile: ./Dockerfile
    links:
      - eurekaserver
      - configserver
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
    ports:
      - "8080:8080"


