language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services: docker
notifications:
  email:
    - pelayochristian.dev@gmail.com
branches:
  only:
    - master
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - mvn install