# TRAVIS
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services: docker
notifications:
  email:
    - pelayochristian.dev@gmail.com
branches:
  only:
    - master
script:
  - mvn install
#  - sh travis_script/deploy_to_docker_hub.sh
#  - sh travis_script/deploy_to_cloud.sh