version: "3"

services:
  eurekaserver:
    build:
      context: ../../eurekaserver
      dockerfile: ./Dockerfile
    hostname: eurekaserver
    ports:
      - "8761:8761"
  configserver:
    build:
      context: ../../configserver
      dockerfile: ./Dockerfile
    hostname: configserver
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
    ports:
      - "8888:8888"
  newsservice:
    build:
      context: ../../newsservice
      dockerfile: ./Dockerfile
    links:
      - eurekaserver
      - configserver
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
      REDIS_HOST: 192.168.1.6
    ports:
      - "8881:8881"
  gatewayserver:
    build:
      context: ../../gatewayserver
      dockerfile: ./Dockerfile
    links:
      - eurekaserver
      - configserver
    environment:
      EUREKA_HOST: eurekaserver
      EUREKA_PORT: 8761
    ports:
      - "8080:8080"


