server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pelayochristian/config-repo/
          searchPaths: newsservice
          username: pelayochristian
          password: chan@082417
          default-label: master
        encrypt:
          enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
